### ISSUE TITLE
Error: Invalid tagname in closing tag

### ISSUE THREAD

**Issue by sumit-raikar** [dmcquay/node-apac#88]
When i try to execute a ItemSearch it is throwing some error like.

![apacerror](https://user-images.githubusercontent.com/19921546/28921095-389d6410-7872-11e7-8bb8-df9d3aab2598.PNG)

Thank you.

**Comment by givo-matan** [comment]
Hi,
I'm experiencing something similar. The package worked fine until recently.
On my windows dev env everything seems to work , But on the Ubuntu production env I get the following error when preforming an itemLookup : 
Error: Unexpected close tag
Line: 9
Column: 165
Char: >
    at error (/home/ubuntu/batman/source/node_modules/sax/lib/sax.js:651:10)
    at strictFail (/home/ubuntu/batman/source/node_modules/sax/lib/sax.js:677:7)
    at closeTag (/home/ubuntu/batman/source/node_modules/sax/lib/sax.js:871:9)
    at Object.write (/home/ubuntu/batman/source/node_modules/sax/lib/sax.js:1436:13)
    at Parser.exports.Parser.Parser.parseString (/home/ubuntu/batman/source/node_modules/xml2js/lib/parser.js:322:31)
    at Parser.parseString (/home/ubuntu/batman/source/node_modules/xml2js/lib/parser.js:5:59)
    at Object.exports.parseString (/home/ubuntu/batman/source/node_modules/xml2js/lib/parser.js:354:19)
    at IncomingMessage.<anonymous> (/home/ubuntu/batman/source/node_modules/apac/lib/operation-helper.js:108:28)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
